/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AttendeesIndexRouteImport } from './routes/attendees/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as AttendeesAttendeeIdRouteImport } from './routes/attendees/$attendeeId'
import { Route as OrgSlugSettingsRouteImport } from './routes/$orgSlug.settings'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdEditRouteImport } from './routes/events/$eventId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesIndexRoute = AttendeesIndexRouteImport.update({
  id: '/attendees/',
  path: '/attendees/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesAttendeeIdRoute = AttendeesAttendeeIdRouteImport.update({
  id: '/attendees/$attendeeId',
  path: '/attendees/$attendeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/$orgSlug/settings',
  path: '/$orgSlug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRoute
  '/attendees/$attendeeId': typeof AttendeesAttendeeIdRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/attendees/': typeof AttendeesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRoute
  '/attendees/$attendeeId': typeof AttendeesAttendeeIdRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/attendees': typeof AttendeesIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRoute
  '/attendees/$attendeeId': typeof AttendeesAttendeeIdRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/attendees/': typeof AttendeesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/login'
    | '/onboarding'
    | '/resources'
    | '/settings'
    | '/signup'
    | '/$orgSlug/settings'
    | '/attendees/$attendeeId'
    | '/invite/$invitationId'
    | '/attendees/'
    | '/events/'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/onboarding'
    | '/resources'
    | '/settings'
    | '/signup'
    | '/$orgSlug/settings'
    | '/attendees/$attendeeId'
    | '/invite/$invitationId'
    | '/attendees'
    | '/events'
    | '/events/$eventId/edit'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/login'
    | '/onboarding'
    | '/resources'
    | '/settings'
    | '/signup'
    | '/$orgSlug/settings'
    | '/attendees/$attendeeId'
    | '/invite/$invitationId'
    | '/attendees/'
    | '/events/'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRoute
  AttendeesAttendeeIdRoute: typeof AttendeesAttendeeIdRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  AttendeesIndexRoute: typeof AttendeesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/': {
      id: '/attendees/'
      path: '/attendees'
      fullPath: '/attendees/'
      preLoaderRoute: typeof AttendeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees/$attendeeId': {
      id: '/attendees/$attendeeId'
      path: '/attendees/$attendeeId'
      fullPath: '/attendees/$attendeeId'
      preLoaderRoute: typeof AttendeesAttendeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/$orgSlug/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRoute,
  AttendeesAttendeeIdRoute: AttendeesAttendeeIdRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  AttendeesIndexRoute: AttendeesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
