/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthOrgRouteImport } from './routes/_auth/_org'
import { Route as AuthOrgIndexRouteImport } from './routes/_auth/_org/index'
import { Route as AuthOrgResourcesRouteImport } from './routes/_auth/_org/resources'
import { Route as AuthOrgCalendarRouteImport } from './routes/_auth/_org/calendar'
import { Route as AuthOrgEventsIndexRouteImport } from './routes/_auth/_org/events/index'
import { Route as AuthOrgAttendeesIndexRouteImport } from './routes/_auth/_org/attendees/index'
import { Route as AuthOrgAttendeesAttendeeIdRouteImport } from './routes/_auth/_org/attendees/$attendeeId'
import { Route as AuthOrgOrgSlugSettingsRouteImport } from './routes/_auth/_org/$orgSlug.settings'
import { Route as AuthOrgEventsEventIdIndexRouteImport } from './routes/_auth/_org/events/$eventId/index'
import { Route as AuthOrgEventsEventIdEditRouteImport } from './routes/_auth/_org/events/$eventId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgRoute = AuthOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgIndexRoute = AuthOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgResourcesRoute = AuthOrgResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgCalendarRoute = AuthOrgCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgEventsIndexRoute = AuthOrgEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgAttendeesIndexRoute = AuthOrgAttendeesIndexRouteImport.update({
  id: '/attendees/',
  path: '/attendees/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgAttendeesAttendeeIdRoute =
  AuthOrgAttendeesAttendeeIdRouteImport.update({
    id: '/attendees/$attendeeId',
    path: '/attendees/$attendeeId',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgOrgSlugSettingsRoute = AuthOrgOrgSlugSettingsRouteImport.update({
  id: '/$orgSlug/settings',
  path: '/$orgSlug/settings',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgEventsEventIdIndexRoute =
  AuthOrgEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgEventsEventIdEditRoute =
  AuthOrgEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => AuthOrgRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthOrgIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/settings': typeof AuthSettingsRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/calendar': typeof AuthOrgCalendarRoute
  '/resources': typeof AuthOrgResourcesRoute
  '/$orgSlug/settings': typeof AuthOrgOrgSlugSettingsRoute
  '/attendees/$attendeeId': typeof AuthOrgAttendeesAttendeeIdRoute
  '/attendees/': typeof AuthOrgAttendeesIndexRoute
  '/events/': typeof AuthOrgEventsIndexRoute
  '/events/$eventId/edit': typeof AuthOrgEventsEventIdEditRoute
  '/events/$eventId/': typeof AuthOrgEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthOrgIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/settings': typeof AuthSettingsRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/calendar': typeof AuthOrgCalendarRoute
  '/resources': typeof AuthOrgResourcesRoute
  '/$orgSlug/settings': typeof AuthOrgOrgSlugSettingsRoute
  '/attendees/$attendeeId': typeof AuthOrgAttendeesAttendeeIdRoute
  '/attendees': typeof AuthOrgAttendeesIndexRoute
  '/events': typeof AuthOrgEventsIndexRoute
  '/events/$eventId/edit': typeof AuthOrgEventsEventIdEditRoute
  '/events/$eventId': typeof AuthOrgEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/_org': typeof AuthOrgRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/_auth/_org/calendar': typeof AuthOrgCalendarRoute
  '/_auth/_org/resources': typeof AuthOrgResourcesRoute
  '/_auth/_org/': typeof AuthOrgIndexRoute
  '/_auth/_org/$orgSlug/settings': typeof AuthOrgOrgSlugSettingsRoute
  '/_auth/_org/attendees/$attendeeId': typeof AuthOrgAttendeesAttendeeIdRoute
  '/_auth/_org/attendees/': typeof AuthOrgAttendeesIndexRoute
  '/_auth/_org/events/': typeof AuthOrgEventsIndexRoute
  '/_auth/_org/events/$eventId/edit': typeof AuthOrgEventsEventIdEditRoute
  '/_auth/_org/events/$eventId/': typeof AuthOrgEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/settings'
    | '/invite/$invitationId'
    | '/calendar'
    | '/resources'
    | '/$orgSlug/settings'
    | '/attendees/$attendeeId'
    | '/attendees/'
    | '/events/'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/settings'
    | '/invite/$invitationId'
    | '/calendar'
    | '/resources'
    | '/$orgSlug/settings'
    | '/attendees/$attendeeId'
    | '/attendees'
    | '/events'
    | '/events/$eventId/edit'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/_org'
    | '/_auth/onboarding'
    | '/_auth/settings'
    | '/invite/$invitationId'
    | '/_auth/_org/calendar'
    | '/_auth/_org/resources'
    | '/_auth/_org/'
    | '/_auth/_org/$orgSlug/settings'
    | '/_auth/_org/attendees/$attendeeId'
    | '/_auth/_org/attendees/'
    | '/_auth/_org/events/'
    | '/_auth/_org/events/$eventId/edit'
    | '/_auth/_org/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_org': {
      id: '/_auth/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthOrgRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_org/': {
      id: '/_auth/_org/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthOrgIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/resources': {
      id: '/_auth/_org/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthOrgResourcesRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/calendar': {
      id: '/_auth/_org/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthOrgCalendarRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/events/': {
      id: '/_auth/_org/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthOrgEventsIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/attendees/': {
      id: '/_auth/_org/attendees/'
      path: '/attendees'
      fullPath: '/attendees/'
      preLoaderRoute: typeof AuthOrgAttendeesIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/attendees/$attendeeId': {
      id: '/_auth/_org/attendees/$attendeeId'
      path: '/attendees/$attendeeId'
      fullPath: '/attendees/$attendeeId'
      preLoaderRoute: typeof AuthOrgAttendeesAttendeeIdRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/$orgSlug/settings': {
      id: '/_auth/_org/$orgSlug/settings'
      path: '/$orgSlug/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AuthOrgOrgSlugSettingsRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/events/$eventId/': {
      id: '/_auth/_org/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthOrgEventsEventIdIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/events/$eventId/edit': {
      id: '/_auth/_org/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AuthOrgEventsEventIdEditRouteImport
      parentRoute: typeof AuthOrgRoute
    }
  }
}

interface AuthOrgRouteChildren {
  AuthOrgCalendarRoute: typeof AuthOrgCalendarRoute
  AuthOrgResourcesRoute: typeof AuthOrgResourcesRoute
  AuthOrgIndexRoute: typeof AuthOrgIndexRoute
  AuthOrgOrgSlugSettingsRoute: typeof AuthOrgOrgSlugSettingsRoute
  AuthOrgAttendeesAttendeeIdRoute: typeof AuthOrgAttendeesAttendeeIdRoute
  AuthOrgAttendeesIndexRoute: typeof AuthOrgAttendeesIndexRoute
  AuthOrgEventsIndexRoute: typeof AuthOrgEventsIndexRoute
  AuthOrgEventsEventIdEditRoute: typeof AuthOrgEventsEventIdEditRoute
  AuthOrgEventsEventIdIndexRoute: typeof AuthOrgEventsEventIdIndexRoute
}

const AuthOrgRouteChildren: AuthOrgRouteChildren = {
  AuthOrgCalendarRoute: AuthOrgCalendarRoute,
  AuthOrgResourcesRoute: AuthOrgResourcesRoute,
  AuthOrgIndexRoute: AuthOrgIndexRoute,
  AuthOrgOrgSlugSettingsRoute: AuthOrgOrgSlugSettingsRoute,
  AuthOrgAttendeesAttendeeIdRoute: AuthOrgAttendeesAttendeeIdRoute,
  AuthOrgAttendeesIndexRoute: AuthOrgAttendeesIndexRoute,
  AuthOrgEventsIndexRoute: AuthOrgEventsIndexRoute,
  AuthOrgEventsEventIdEditRoute: AuthOrgEventsEventIdEditRoute,
  AuthOrgEventsEventIdIndexRoute: AuthOrgEventsEventIdIndexRoute,
}

const AuthOrgRouteWithChildren =
  AuthOrgRoute._addFileChildren(AuthOrgRouteChildren)

interface AuthRouteChildren {
  AuthOrgRoute: typeof AuthOrgRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOrgRoute: AuthOrgRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
